apiVersion: apps/v1
kind: Deployment
metadata:
  name: @REPO_NAME@
spec:
  selector:
    matchLabels:
      app: @REPO_NAME@
  template:
    metadata:
      labels:
        app: @REPO_NAME@
    spec:
      containers:
      - name: @REPO_NAME@
        image: @IMAGE_NAME@
        ports:
        - containerPort: 5051
---
apiVersion: v1
kind: Service
metadata:
  name: @REPO_NAME@-ilb
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  loadBalancerIP: @ILB_IP@
  externalTrafficPolicy: Cluster
  selector:
    app: @REPO_NAME@
  ports:
  - name: grpc5051
    port: 5051
    targetPort: 5051
    protocol: TCP
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view-binding # This is so Faasd-Worker can access the control plane to retrieve the artifact-id of the pod its running on
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io